// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(document).ready(function() {
    var currentRot, distance, down, left, movement, right, storePos, up, url;
    distance = "30px";
    up = {
      bottom: "+=" + distance
    };
    down = {
      bottom: "-=" + distance
    };
    left = {
      left: "-=" + distance
    };
    right = {
      left: "+=" + distance
    };
    movement = {
      87: {
        bot: {
          forward: 0.3
        },
        rotation: {
          0: up,
          90: right,
          180: down,
          270: left
        }
      },
      83: {
        bot: {
          forward: -0.3
        },
        rotation: {
          0: down,
          90: left,
          180: up,
          270: right
        }
      },
      65: {
        bot: {
          strafe: -1
        },
        rotation: {
          0: left,
          90: up,
          180: right,
          270: down
        }
      },
      68: {
        bot: {
          strafe: 1
        },
        rotation: {
          0: right,
          90: down,
          180: left,
          270: up
        }
      },
      37: {
        bot: {
          turn: -1
        },
        turn: function() {
          currentRot -= 90;
          return $('#testcar').css({
            "transform": "rotate(" + currentRot + "deg)"
          });
        }
      },
      39: {
        bot: {
          turn: 1
        },
        turn: function() {
          currentRot += 90;
          return $('#testcar').css({
            "transform": "rotate(" + currentRot + "deg)"
          });
        }
      }
    };
    url = "http://192.168.0.105:8071/motion-control/update";
    currentRot = 0;
    storePos = function(currentRot) {
      if ((currentRot < 0) && (currentRot % 360 !== 0)) {
        return (currentRot % 360) + 360;
      } else {
        return currentRot % 360;
      }
    };
    return $(document).keydown(function(keyObject) {
      var direction, key, reset;
      key = parseInt(keyObject.which, 10);
      direction = storePos(currentRot);
      reset = function() {
        return $.ajax(url, {
          dataType: "jsonp",
          data: {
            strafe: 0
          }
        });
      };
      if (movement[key] !== null) {
        if (key !== 37 && key !== 39) {
          $('#testcar').animate(movement[key].rotation[direction], 100);
        } else {
          movement[key].turn();
        }
        $.ajax(url, {
          dataType: "jsonp",
          data: movement[key].bot
        });
        return setTimeout(function() {
          return reset();
        }, 1000);
      }
    });
  });

}).call(this);
